name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      
    - name: Run tests
      run: cargo test --verbose
    
    # Count total number of tests and update badge in README
    - name: Count tests
      id: count_tests
      run: |
        TEST_COUNT=$(.github/scripts/count_tests.sh)
        echo "test_count=$TEST_COUNT" >> $GITHUB_OUTPUT
        echo "Total tests: $TEST_COUNT"
    
    - name: Update test badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        .github/scripts/update_test_badge.sh ${{ steps.count_tests.outputs.test_count }}
        
    - name: Commit badge update
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update test count badge to ${{ steps.count_tests.outputs.test_count }}"
        file_pattern: "README.md"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
